import Foundation

enum LocalAskIntent: String, Codable, CaseIterable, Hashable {
    case metric
    case medication
    case followUp
    case freeText
}

enum LocalAskTimeSelection: String, Codable, Equatable {
    case allTime
    case interval
    case mostRecent
    case earliest
}

struct LocalAskTimeScope: Equatable {
    var selection: LocalAskTimeSelection
    var interval: DateInterval?
    var displayLabel: String
    var didFallback: Bool

    static let allTime = LocalAskTimeScope(
        selection: .allTime,
        interval: nil,
        displayLabel: "全部时间",
        didFallback: false
    )

    func contains(_ date: Date) -> Bool {
        interval?.contains(date) ?? true
    }
}

struct LocalAskMetricFact: Equatable, Identifiable {
    var id: UUID
    var sourceRecordID: UUID
    var name: String
    var numericValue: Double?
    var textualValue: String?
    var unit: String
    var referenceLow: Double?
    var referenceHigh: Double?
    var referenceText: String?
    var abnormalState: LabFlag
    var recordedAt: Date
}

struct LocalAskMedicationFact: Equatable, Identifiable {
    var id: UUID
    var sourceRecordID: UUID?
    var name: String
    var doseValue: Double?
    var doseUnit: String
    var frequency: FrequencyPreset
    var startDate: Date
    var endDate: Date?
    var lifecycleStatus: MedicationLifecycleStatus
}

struct LocalAskFollowUpFact: Equatable, Identifiable {
    var id: UUID
    var sourceRecordID: UUID?
    var plannedDate: Date
    var items: [String]
    var status: FollowUpStatus
    var completedAt: Date?
}

enum LocalAskSourceRoute: Equatable {
    case record(UUID)
    case medication(UUID)
    case followUp(UUID)

    static func medication(
        sourceRecordID: UUID?,
        medicationID: UUID,
        availableRecordIDs: Set<UUID>
    ) -> LocalAskSourceRoute {
        if let sourceRecordID,
           availableRecordIDs.contains(sourceRecordID) {
            return .record(sourceRecordID)
        }
        return .medication(medicationID)
    }

    static func followUp(
        sourceRecordID: UUID?,
        followUpID: UUID,
        availableRecordIDs: Set<UUID>
    ) -> LocalAskSourceRoute {
        if let sourceRecordID,
           availableRecordIDs.contains(sourceRecordID) {
            return .record(sourceRecordID)
        }
        return .followUp(followUpID)
    }
}

struct LocalAskHospitalFact: Equatable, Identifiable {
    var id: UUID { sourceRecordID }
    var name: String
    var latestVisitAt: Date
    var visitCount: Int
    var sourceRecordID: UUID
}

struct LocalAskRecordHit: Equatable, Identifiable {
    var id: UUID { recordID }
    var recordID: UUID
    var title: String
    var summary: String
    var eventDate: Date
    var score: Double
    var matchedTerms: [String]
}

struct LocalAskResponse: Equatable {
    static let factualDisclaimer = "以下是从你的资料里找到的原始记录，CareThread 不做医学判断。"

    var intents: [LocalAskIntent]
    var timeScope: LocalAskTimeScope
    var metricFacts: [LocalAskMetricFact]
    var medicationFacts: [LocalAskMedicationFact]
    var followUpFacts: [LocalAskFollowUpFact]
    var hospitalFacts: [LocalAskHospitalFact]
    var recordHits: [LocalAskRecordHit]
    /// Reserved for a future on-device factual overview. Phase one leaves it nil.
    var factualOverview: String?

    var scopeNotice: String {
        if timeScope.didFallback {
            return "未识别到明确时间，已查找全部资料。"
        }
        return "查找范围：\(timeScope.displayLabel)"
    }

    var rankedSourceRecordIDs: [UUID] {
        var seen = Set<UUID>()
        let candidates = metricFacts.map(\.sourceRecordID)
            + medicationFacts.compactMap(\.sourceRecordID)
            + followUpFacts.compactMap(\.sourceRecordID)
            + hospitalFacts.map(\.sourceRecordID)
            + recordHits.map(\.recordID)
        return candidates.filter { seen.insert($0).inserted }
    }

    /// All text generated by CareThread itself. Source titles and source content
    /// are deliberately excluded because they remain verbatim local evidence.
    var generatedDisplayText: String {
        [Self.factualDisclaimer, scopeNotice, factualOverview]
            .compactMap { $0 }
            .joined(separator: "\n")
    }
}

struct LocalAskIndexedDocument: Codable, Equatable, Sendable {
    var recordID: UUID
    var sourceRevision: Int
    var weightedTermFrequencies: [String: Double]
    var termCount: Int
}

struct LocalAskPosting: Equatable, Sendable {
    var recordID: UUID
    var weightedFrequency: Double
}

/// Runtime-only corpus assembled from the persisted per-record index shards.
/// Keeping postings out of SwiftData preserves cheap incremental shard updates,
/// while queries can obtain candidates and document frequencies without a
/// full-corpus scan.
struct LocalAskInvertedIndex: Equatable, Sendable {
    var postingsByTerm: [String: [LocalAskPosting]]
    var recordsByID: [UUID: LocalAskPreparedRecord]
    var documentTermCounts: [UUID: Int]

    init(records: [LocalAskPreparedRecord]) {
        var postings: [String: [LocalAskPosting]] = [:]
        var recordsByID: [UUID: LocalAskPreparedRecord] = [:]
        var documentTermCounts: [UUID: Int] = [:]
        recordsByID.reserveCapacity(records.count)
        documentTermCounts.reserveCapacity(records.count)

        for record in records {
            let recordID = record.snapshot.id
            recordsByID[recordID] = record
            documentTermCounts[recordID] = record.document.termCount
            for (term, frequency) in record.document.weightedTermFrequencies
            where frequency > 0 {
                postings[term, default: []].append(
                    LocalAskPosting(
                        recordID: recordID,
                        weightedFrequency: frequency
                    )
                )
            }
        }
        for term in Array(postings.keys) {
            postings[term]?.sort {
                $0.recordID.uuidString < $1.recordID.uuidString
            }
        }
        self.postingsByTerm = postings
        self.recordsByID = recordsByID
        self.documentTermCounts = documentTermCounts
    }

    func candidateRecordIDs(
        for terms: [String],
        allowedRecordIDs: Set<UUID>
    ) -> Set<UUID> {
        var candidates = Set<UUID>()
        for term in terms {
            for posting in postingsByTerm[term] ?? []
            where allowedRecordIDs.contains(posting.recordID) {
                candidates.insert(posting.recordID)
            }
        }
        return candidates
    }
}

struct LocalAskWeightedText: Sendable {
    var text: String
    var weight: Double
}

struct LocalAskIndexInput: Sendable {
    var recordID: UUID
    var sourceRevision: Int
    var fragments: [LocalAskWeightedText]
}

struct LocalAskRecordSnapshot: Equatable, @unchecked Sendable {
    var id: UUID
    var patientID: UUID
    var title: String
    var summary: String
    var eventDate: Date
    var type: RecordType
    var hospital: String?
    var department: String?
    var doctor: String?
    var primaryDisease: String?
    var ocrText: String?
    var structuredFields: [KeyValueItem]
    var measurements: [LocalAskMetricFact]
    var tags: [LocalAskTagSnapshot]
}

struct LocalAskTagSnapshot: Equatable {
    var kind: RecordTagKind
    var value: String
}

struct LocalAskMedicationSnapshot: Equatable {
    var id: UUID
    var patientID: UUID
    var sourceRecordID: UUID?
    var name: String
    var doseValue: Double?
    var doseUnit: String
    var frequency: FrequencyPreset
    var startDate: Date
    var endDate: Date?
    var lifecycleStatus: MedicationLifecycleStatus
}

struct LocalAskFollowUpSnapshot: Equatable {
    var id: UUID
    var patientID: UUID
    var sourceRecordID: UUID?
    var plannedDate: Date
    var items: [String]
    var status: FollowUpStatus
    var completedAt: Date?
}

struct LocalAskPreparedRecord: Equatable, @unchecked Sendable {
    var snapshot: LocalAskRecordSnapshot
    var document: LocalAskIndexedDocument
}

struct LocalAskPreparedData: Equatable {
    var memberID: UUID
    var records: [LocalAskPreparedRecord]
    var medications: [LocalAskMedicationSnapshot]
    var followUps: [LocalAskFollowUpSnapshot]
    var invertedIndex: LocalAskInvertedIndex

    init(
        memberID: UUID,
        records: [LocalAskPreparedRecord],
        medications: [LocalAskMedicationSnapshot],
        followUps: [LocalAskFollowUpSnapshot],
        invertedIndex: LocalAskInvertedIndex? = nil
    ) {
        self.memberID = memberID
        self.records = records
        self.medications = medications
        self.followUps = followUps
        self.invertedIndex = invertedIndex
            ?? LocalAskInvertedIndex(records: records)
    }
}
