import Foundation

enum MemberProfileCopy {
    static let membersTitle = "家人档案"
    static let membersSubtitle = "最多 20 位；每位成员的病历和原件彼此独立。"
    static let addMember = "添加家人"
    static let switchMember = "切换到此成员"
    static let selected = "当前"
    static let limitReached = "已达到 20 位成员上限。"
    static let deleteMember = "删除成员"
    static let deleteMemberTitle = "永久删除这位成员？"
    static let deleteMemberWarning = "将永久删除此成员的全部病程资料和本地原文件。删除前请先导出备份；此操作无法撤销。"
    static let deleteSelectedMemberWarning = "这是当前成员。删除后会自动切换到下一位成员。其全部病程资料和本地原文件将永久删除；请先导出备份。此操作无法撤销。"
    static let profileTitle = "成员资料"
    static let identity = "身份与报告匹配"
    static let displayName = "日常称呼"
    static let reportName = "报告姓名"
    static let aliases = "姓名别名"
    static let birthDate = "出生日期"
    static let gender = "性别说明"
    static let health = "主要情况"
    static let conditions = "病种或长期情况"
    static let allergies = "过敏信息"
    static let histories = "重要病史"
    static let questions = "问医生的问题与就诊笔记"
    static let revisions = "修订历史"
    static let undo = "撤销最近一次修改"
    static let save = "保存"
    static let saved = "资料已保存"
    static let conflict = "资料已在其他页面更新，请检查刷新后的内容。"
    static let onePerLine = "每行一项"
    static let noQuestions = "还没有待问问题或就诊笔记"
    static let addQuestion = "添加问题"
    static let pending = "待问"
    static let answered = "已回答"
    static let answer = "手动记录回答"
    static let note = "就诊笔记"
    static let noSensitiveLogs = "修订历史只展示时间和字段名称，不展示健康正文。"
}
