import Foundation

enum BackupCopy {
    static let navigationTitle = "备份与恢复"
    static let exportTitle = "导出备份"
    static let exportDescription = Copy.exportNotice
    static let scope = "导出范围"
    static let currentMember = "当前家人"
    static let allMembers = "全部家人"
    static let prepareExport = "生成备份"
    static let prepareEncryptedExport = "生成加密备份"
    static let readableExport = "导出人读 ZIP"
    static let readableWarning = "人读 ZIP 没有口令加密，只应在你主动需要用 Mac 查看时导出。"
    static let password = "备份口令"
    static let passwordHint = "至少 12 个字符；恢复时必须使用同一口令"
    static let shareExport = "分享备份"
    static let lastExport = "上次导出"
    static let importTitle = "从备份恢复"
    static let importDescription = "恢复前会先验证全部文件，并保留当前数据库和原件快照。校验或恢复失败时，现有资料不会被替换。"
    static let chooseBackup = "选择备份文件"
    static let validationTitle = "备份校验通过"
    static let exportedAt = "备份时间"
    static let memberCount = "家人数"
    static let recordCount = "记录数"
    static let attachmentCount = "原件数"
    static let restoreQuestion = "用这份备份替换当前数据？"
    static let restoreWarning = "当前全部记录将被替换。CareThread 会先保留一份自动快照以防万一。"
    static let restore = "恢复"
    static let cancel = "取消"
    static let restored = "备份恢复完成"
    static let sensitive = "备份含完整健康资料与原件。只保存到你信任的位置，不要发送给不可信的人。"
    static let working = "正在安全处理…"
    static let debugPrepare = "准备 U10 测试备份"
    static let debugClear = "DEBUG 清空全库"
    static let debugRestore = "导入最近测试备份"
    static let debugCountFormat = "当前记录：%d"
}
