import Foundation

enum BackupCopy {
    static let navigationTitle = "备份与恢复"
    static let transferTitle = "换新手机"
    static let transferDescription = "两台 iPhone 放在一起直接传输，不用设口令，也不用先保管文件。"
    static let openTransfer = "去换机传输"
    static let exportTitle = "导出存档"
    static let exportDescription = "保存一份完整存档，以防手机丢失；也可以在电脑上直接打开其中的资料。"
    static let scope = "导出范围"
    static let currentMember = "当前家人"
    static let allMembers = "全部家人"
    static let prepareExport = "生成存档"
    static let optionalPassword = "给这个文件设个口令（可选）"
    static let prepareEncryptedExport = "生成带口令的存档"
    static let exportRisk = "这个文件谁拿到都能看全部病历，别发到聊天工具或放进共享云盘。"
    static let password = "文件口令"
    static let passwordHint = "至少 12 个字符。它只锁住这份导出文件，不是应用锁。"
    static let passwordLossWarning = "忘记口令，这个文件就永远打不开；CareThread 无法找回。"
    static let shareExport = "保存或分享存档"
    static let lastExport = "上次导出"
    static let importTitle = "从存档恢复"
    static let importDescription = "先选择文件。CareThread 会验证全部内容，并在替换前保留本机快照；失败时现有资料不会改变。"
    static let chooseBackup = "选择存档文件"
    static let encryptedImport = "这份存档设有口令"
    static let validateEncryptedImport = "用这个口令验证"
    static let validationTitle = "存档校验通过"
    static let exportedAt = "存档时间"
    static let memberCount = "家人数"
    static let recordCount = "记录数"
    static let attachmentCount = "原件数"
    static let restoreQuestion = "用这份备份替换当前数据？"
    static let restoreWarning = "当前全部记录将被替换。CareThread 会先保留一份自动快照以防万一。"
    static let restore = "恢复"
    static let cancel = "取消"
    static let restored = "存档恢复完成"
    static let working = "正在安全处理…"
    static let debugPrepare = "准备 U10 测试存档"
    static let debugClear = "DEBUG 清空全库"
    static let debugRestore = "导入最近测试存档"
    static let debugCountFormat = "当前记录：%d"
}
