import Foundation

extension Copy.Elder {
    static let settings = "设置"
    static let records = "记录"
    static let currentMember = "当前是"
    static let switchMember = "切换家人"
    static let medications = "今天的药"
    static let nextFollowUp = "下次复查"
    static let doctorBrief = "给医生看"
    static let noFollowUp = "目前没有待复查安排。"
    static let pendingExplanation = "请家人在标准版里核对"
    static let captureCamera = "拍照"
    static let capturePhotos = "从相册选"
    static let captureFixture = "测试样张"
    static let multiPageHint = "这次选中的多张图片会存成同一份报告。不同报告请分开录入。"
    static let todayChoice = "就是今天"
    static let chooseDate = "选日期"
    static let captureAgain = "再拍一张"
    static let backToday = "回到今天"
    static let saving = "正在本机存好"
    static let saveFailed = "这次没有存好，原有资料没有被修改。请重试。"
    static let identityReviewNeeded = "识别到的姓名需要家人核对。原件和草稿已安全保留，请切回标准版处理。"
    static let noRecords = "还没有报告。点中间的“拍照存报告”就能开始。"
    static let viewOriginal = "看原件"
    static let editRecord = "更正这份资料"
    static let hospitalMissing = "还没有填写医院"
    static let recordSummaryEmpty = "这份资料还没有填写摘要。"
    static let doctorEmpty = "先拍几份报告进来，这里会自动整理成给医生看的一页。"
    static let exportPrint = "导出 / 打印"
    static let reminders = "提醒"
    static let fontSize = "字体大小"
    static let switchStandard = "切换回标准版"
    static let about = "关于与免责"
    static let disclaimerTitle = "重要说明"
    static let recordDateHospital = "日期和医院"
}
